import type { GalleryImage } from "./data";

/* Official Kia product photography, sourced from CarDekho's per-model
   image galleries (cardekho.com/kia/{model}/pictures) — the same real
   photos used across Indian automotive listings, not manufacturer
   marketing renders. Every URL below was extracted directly from each
   model's own gallery page and curl-verified live (HTTP 200) during this
   build. Labels are derived from CarDekho's own filenames.

   Syros EV is pre-launch (Kia opened pre-booking, not yet on sale), but
   CarDekho already has genuine teaser photography for it — used as-is
   rather than reusing another model's gallery. */

const g = (label: string, url: string): GalleryImage => ({
  src: url,
  alt: `${label} photo`,
  label,
});

export const carGallery: Record<string, GalleryImage[]> = {
  seltos: [
    g("Front Three-Quarter", "/gallery/seltos/front-left-side-47.jpg"),
    g("Front View", "/gallery/seltos/front-view-118.jpg"),
    g("Side Profile", "/gallery/seltos/side-view-_left_-90.jpg"),
    g("Rear Three-Quarter", "/gallery/seltos/rear-left-view-121.jpg"),
    g("Rear View", "/gallery/seltos/rear-view-119.jpg"),
    g("Front Grille", "/gallery/seltos/grille-97.jpg"),
    g("Headlight", "/gallery/seltos/headlight-43.jpg"),
    g("Taillight", "/gallery/seltos/taillight-44.jpg"),
    g("Alloy Wheel", "/gallery/seltos/wheel-42.jpg"),
    g("Front Bumper", "/gallery/seltos/front-bumper-222.jpg"),
    g("Rear Bumper", "/gallery/seltos/rear-bumper-234.jpg"),
    g("Dashboard", "/gallery/seltos/dashboard-59.jpg"),
    g("Steering Wheel", "/gallery/seltos/steering-wheel-54.jpg"),
    g("Instrument Cluster", "/gallery/seltos/instrument-cluster-62.jpg"),
    g("Front Seats", "/gallery/seltos/door-view-of-driver-seat-51.jpg"),
    g("Rear Seats", "/gallery/seltos/rear-seats-131.jpg"),
    g("Boot Space", "/gallery/seltos/boot-_open_-122.jpg"),
    g("Infotainment System", "/gallery/seltos/infotainment-system-main-menu-183.jpg"),
    g("AC Controls", "/gallery/seltos/ac-controls-289.jpg"),
    g("Sunroof", "/gallery/seltos/sun-roof-moon-roof-81.jpg"),
  ],
  sonet: [
    g("Front Three-Quarter", "/gallery/sonet/front-left-side-47.jpg"),
    g("Front View", "/gallery/sonet/front-view-118.jpg"),
    g("Side Profile", "/gallery/sonet/side-view-_left_-90.jpg"),
    g("Rear Three-Quarter", "/gallery/sonet/rear-left-view-121.jpg"),
    g("Rear View", "/gallery/sonet/rear-view-119.jpg"),
    g("Front Grille", "/gallery/sonet/grille-97.jpg"),
    g("Headlight", "/gallery/sonet/headlight-43.jpg"),
    g("Taillight", "/gallery/sonet/taillight-44.jpg"),
    g("Alloy Wheel", "/gallery/sonet/wheel-42.jpg"),
    g("Front Bumper", "/gallery/sonet/front-bumper-222.jpg"),
    g("Rear Bumper", "/gallery/sonet/rear-bumper-234.jpg"),
    g("Dashboard", "/gallery/sonet/dashboard-59.jpg"),
    g("Steering Wheel", "/gallery/sonet/steering-wheel-54.jpg"),
    g("Instrument Cluster", "/gallery/sonet/instrument-cluster-62.jpg"),
    g("Front Seats", "/gallery/sonet/door-view-of-driver-seat-51.jpg"),
    g("Rear Seats", "/gallery/sonet/rear-seats-52.jpg"),
    g("Boot Space", "/gallery/sonet/boot-_open_-122.jpg"),
    g("Infotainment System", "/gallery/sonet/infotainment-system-main-menu-183.jpg"),
    g("AC Controls", "/gallery/sonet/ac-controls-151.jpg"),
    g("Sunroof", "/gallery/sonet/sun-roof-moon-roof-81.jpg"),
  ],
  syros: [
    g("Front Three-Quarter", "/gallery/syros/front-left-side-47.jpg"),
    g("Front View", "/gallery/syros/front-view-118.jpg"),
    g("Rear View", "/gallery/syros/rear-view-119.jpg"),
    g("Front Grille", "/gallery/syros/grille-97.jpg"),
    g("Headlight", "/gallery/syros/headlight-43.jpg"),
    g("Taillight", "/gallery/syros/taillight-44.jpg"),
    g("Alloy Wheel", "/gallery/syros/wheel-42.jpg"),
    g("Front Bumper", "/gallery/syros/front-bumper-222.jpg"),
    g("Rear Bumper", "/gallery/syros/rear-bumper-234.jpg"),
    g("Dashboard", "/gallery/syros/dashboard-59.jpg"),
    g("Steering Wheel", "/gallery/syros/steering-wheel-54.jpg"),
    g("Window Line", "/gallery/syros/window-line-158.jpg"),
    g("Front Wiper", "/gallery/syros/front-wiper-96.jpg"),
    g("Side Mirror", "/gallery/syros/side-mirror-_body_-93.jpg"),
    g("Side Skirt", "/gallery/syros/side-skirt-230.jpg"),
    g("Roof Rails", "/gallery/syros/roof-rails-124.jpg"),
    g("Rear Spoiler", "/gallery/syros/rear-spoiler-233.jpg"),
    g("Rear Windshield", "/gallery/syros/rear-windshield-235.jpg"),
    g("Boot Closed", "/gallery/syros/boot-closed-236.jpg"),
    g("Front Fog Lamp", "/gallery/syros/front-fog-lamp-41.jpg"),
    g("Model Badging", "/gallery/syros/model-and-badging-100.jpg"),
  ],
  carens: [
    g("Front Three-Quarter", "/gallery/carens/front-left-side-47.jpg"),
    g("Front View", "/gallery/carens/front-view-118.jpg"),
    g("Side Profile", "/gallery/carens/side-view-_left_-90.jpg"),
    g("Rear Three-Quarter", "/gallery/carens/rear-left-view-121.jpg"),
    g("Rear View", "/gallery/carens/rear-view-119.jpg"),
    g("Front Grille", "/gallery/carens/grille-97.jpg"),
    g("Headlight", "/gallery/carens/headlight-43.jpg"),
    g("Taillight", "/gallery/carens/taillight-44.jpg"),
    g("Alloy Wheel", "/gallery/carens/wheel-42.jpg"),
    g("Dashboard", "/gallery/carens/dashboard-59.jpg"),
    g("Door Handle", "/gallery/carens/door-handle-45.jpg"),
    g("Rear Windshield", "/gallery/carens/rear-windshield-235.jpg"),
    g("Airbags", "/gallery/carens/airbags-94.jpg"),
    g("Seat Headrest", "/gallery/carens/seat-headrest-200.jpg"),
    g("Seat Adjustment", "/gallery/carens/seat-adjustment-191.jpg"),
    g("Rear Headrest", "/gallery/carens/rear-head-rest-273.jpg"),
    g("Android Auto", "/gallery/carens/android-auto-_wired-wireless_-283.jpg"),
    g("Roof AC Vents", "/gallery/carens/roof-mounted-ac-vents-196.jpg"),
    g("Centre Console Storage", "/gallery/carens/center-tunnel-with-attached-smartphone-123.jpg"),
    g("Curtain Airbags", "/gallery/carens/rear-side-curtains-147.jpg"),
  ],
  "carens-clavis": [
    g("Front Three-Quarter", "/gallery/carens-clavis/front-left-side-47.jpg"),
    g("Front View", "/gallery/carens-clavis/front-view-118.jpg"),
    g("Side Profile", "/gallery/carens-clavis/side-view-_left_-90.jpg"),
    g("Rear Three-Quarter", "/gallery/carens-clavis/rear-left-view-121.jpg"),
    g("Rear View", "/gallery/carens-clavis/rear-view-119.jpg"),
    g("Front Grille", "/gallery/carens-clavis/grille-97.jpg"),
    g("Headlight", "/gallery/carens-clavis/headlight-43.jpg"),
    g("Taillight", "/gallery/carens-clavis/taillight-44.jpg"),
    g("Alloy Wheel", "/gallery/carens-clavis/wheel-42.jpg"),
    g("Front Bumper", "/gallery/carens-clavis/front-bumper-222.jpg"),
    g("Rear Bumper", "/gallery/carens-clavis/rear-bumper-234.jpg"),
    g("Dashboard", "/gallery/carens-clavis/dashboard-59.jpg"),
    g("Steering Wheel", "/gallery/carens-clavis/steering-wheel-54.jpg"),
    g("Instrument Cluster", "/gallery/carens-clavis/instrument-cluster-62.jpg"),
    g("Front Seats", "/gallery/carens-clavis/door-view-of-driver-seat-51.jpg"),
    g("Rear Seats", "/gallery/carens-clavis/rear-seats-with-arm-rest-193.jpg"),
    g("Boot Space", "/gallery/carens-clavis/boot-_open_-122.jpg"),
    g("Infotainment System", "/gallery/carens-clavis/infotainment-system-main-menu-183.jpg"),
    g("AC Controls", "/gallery/carens-clavis/ac-controls-151.jpg"),
    g("Sunroof", "/gallery/carens-clavis/sun-roof-moon-roof-81.jpg"),
  ],
  "carens-clavis-ev": [
    g("Front Three-Quarter", "/gallery/carens-clavis-ev/front-left-side-47.jpg"),
    g("Front View", "/gallery/carens-clavis-ev/front-view-118.jpg"),
    g("Side Profile", "/gallery/carens-clavis-ev/side-view-_left_-90.jpg"),
    g("Rear Three-Quarter", "/gallery/carens-clavis-ev/rear-left-view-121.jpg"),
    g("Rear View", "/gallery/carens-clavis-ev/rear-view-119.jpg"),
    g("Front Grille", "/gallery/carens-clavis-ev/grille-97.jpg"),
    g("Headlight", "/gallery/carens-clavis-ev/headlight-43.jpg"),
    g("Taillight", "/gallery/carens-clavis-ev/taillight-44.jpg"),
    g("Alloy Wheel", "/gallery/carens-clavis-ev/wheel-42.jpg"),
    g("Front Bumper", "/gallery/carens-clavis-ev/front-bumper-222.jpg"),
    g("Rear Bumper", "/gallery/carens-clavis-ev/rear-bumper-234.jpg"),
    g("Dashboard", "/gallery/carens-clavis-ev/dashboard-59.jpg"),
    g("Steering Wheel", "/gallery/carens-clavis-ev/steering-wheel-54.jpg"),
    g("Front Seats", "/gallery/carens-clavis-ev/door-view-of-driver-seat-51.jpg"),
    g("Rear Seats", "/gallery/carens-clavis-ev/rear-seats-52.jpg"),
    g("Boot Space", "/gallery/carens-clavis-ev/boot-_open_-122.jpg"),
    g("Infotainment System", "/gallery/carens-clavis-ev/infotainment-system-main-menu-183.jpg"),
    g("AC Controls", "/gallery/carens-clavis-ev/ac-controls-151.jpg"),
    g("Sunroof", "/gallery/carens-clavis-ev/sun-roof-moon-roof-81.jpg"),
    g("Charging Port", "/gallery/carens-clavis-ev/ev-charging-port-closed-228.jpg"),
  ],
  carnival: [
    g("Front Three-Quarter", "/gallery/carnival/front-left-side-47.jpg"),
    g("Front View", "/gallery/carnival/front-view-118.jpg"),
    g("Side Profile", "/gallery/carnival/side-view-_left_-90.jpg"),
    g("Rear Three-Quarter", "/gallery/carnival/rear-left-view-121.jpg"),
    g("Rear View", "/gallery/carnival/rear-view-119.jpg"),
    g("Front Grille", "/gallery/carnival/grille-97.jpg"),
    g("Headlight", "/gallery/carnival/headlight-43.jpg"),
    g("Taillight", "/gallery/carnival/taillight-44.jpg"),
    g("Alloy Wheel", "/gallery/carnival/wheel-42.jpg"),
    g("Front Bumper", "/gallery/carnival/front-bumper-222.jpg"),
    g("Rear Bumper", "/gallery/carnival/rear-bumper-234.jpg"),
    g("Dashboard", "/gallery/carnival/dashboard-59.jpg"),
    g("Steering Wheel", "/gallery/carnival/steering-wheel-54.jpg"),
    g("Instrument Cluster", "/gallery/carnival/instrument-cluster-62.jpg"),
    g("Front Seats", "/gallery/carnival/door-view-of-driver-seat-51.jpg"),
    g("Infotainment System", "/gallery/carnival/infotainment-system-main-menu-183.jpg"),
    g("AC Controls", "/gallery/carnival/ac-controls-151.jpg"),
    g("Front Wiper", "/gallery/carnival/front-wiper-96.jpg"),
    g("Side Mirror", "/gallery/carnival/side-mirror-_body_-93.jpg"),
    g("Door Handle", "/gallery/carnival/door-handle-45.jpg"),
  ],
  ev6: [
    g("Front Three-Quarter", "/gallery/ev6/front-left-side-47.jpg"),
    g("Front View", "/gallery/ev6/front-view-118.jpg"),
    g("Side Profile", "/gallery/ev6/side-view-_left_-90.jpg"),
    g("Rear Three-Quarter", "/gallery/ev6/rear-left-view-121.jpg"),
    g("Rear View", "/gallery/ev6/rear-view-119.jpg"),
    g("Front Grille", "/gallery/ev6/grille-97.jpg"),
    g("Headlight", "/gallery/ev6/headlight-43.jpg"),
    g("Taillight", "/gallery/ev6/taillight-44.jpg"),
    g("Alloy Wheel", "/gallery/ev6/wheel-42.jpg"),
    g("Rear Bumper", "/gallery/ev6/rear-bumper-234.jpg"),
    g("Dashboard", "/gallery/ev6/dashboard-59.jpg"),
    g("Steering Wheel", "/gallery/ev6/steering-wheel-54.jpg"),
    g("Instrument Cluster", "/gallery/ev6/instrument-cluster-62.jpg"),
    g("Front Seats", "/gallery/ev6/door-view-of-driver-seat-51.jpg"),
    g("Rear Seats", "/gallery/ev6/rear-seats-52.jpg"),
    g("Boot Space", "/gallery/ev6/open-trunk-49.jpg"),
    g("Infotainment System", "/gallery/ev6/infotainment-system-main-menu-183.jpg"),
    g("AC Controls", "/gallery/ev6/ac-controls-151.jpg"),
    g("Sunroof", "/gallery/ev6/sun-roof-moon-roof-81.jpg"),
    g("Charging Port", "/gallery/ev6/ev-charging-port-closed-228.jpg"),
  ],
  ev9: [
    g("Front Three-Quarter", "/gallery/ev9/front-left-side-47.jpg"),
    g("Front View", "/gallery/ev9/front-view-118.jpg"),
    g("Side Profile", "/gallery/ev9/side-view-_left_-90.jpg"),
    g("Front Grille", "/gallery/ev9/grille-97.jpg"),
    g("Alloy Wheel", "/gallery/ev9/wheel-42.jpg"),
    g("Dashboard", "/gallery/ev9/dashboard-59.jpg"),
    g("Steering Wheel", "/gallery/ev9/steering-wheel-54.jpg"),
    g("Sunroof", "/gallery/ev9/sun-roof-moon-roof-81.jpg"),
    g("Rear Three-Quarter", "/gallery/ev9/rear-right-side-48.jpg"),
    g("Side Profile (Right)", "/gallery/ev9/side-view-_right_-38.jpg"),
    g("Top View", "/gallery/ev9/top-view-117.jpg"),
    g("Exterior Detail", "/gallery/ev9/exterior-image-165.jpg"),
    g("Steering Controls", "/gallery/ev9/recessed-steering-controls-139.jpg"),
    g("Rear Seats (Aerial View)", "/gallery/ev9/seats-_aerial-view_-53.jpg"),
    g("Parking Camera Display", "/gallery/ev9/parking-camera-display-136.jpg"),
    g("Speakers", "/gallery/ev9/speakers-58.jpg"),
    g("Interior Detail", "/gallery/ev9/interior-image-207.jpg"),
  ],
  "syros-ev": [
    g("Front Three-Quarter", "/gallery/syros-ev/front-left-side-47.jpg"),
    g("Front View", "/gallery/syros-ev/front-view-118.jpg"),
    g("Side Profile", "/gallery/syros-ev/side-view-_left_-90.jpg"),
    g("Rear Three-Quarter", "/gallery/syros-ev/rear-left-view-121.jpg"),
    g("Rear View", "/gallery/syros-ev/rear-view-119.jpg"),
    g("Alloy Wheel", "/gallery/syros-ev/wheel-42.jpg"),
    g("Front Bumper", "/gallery/syros-ev/front-bumper-222.jpg"),
    g("Charging Port", "/gallery/syros-ev/ev-charging-port-closed-228.jpg"),
    g("Instrument Cluster", "/gallery/syros-ev/instrument-cluster-62.jpg"),
    g("Gear Shifter", "/gallery/syros-ev/gear-shifter-87.jpg"),
    g("Sunroof", "/gallery/syros-ev/sunroof-_outside_-232.jpg"),
    g("Door Handle", "/gallery/syros-ev/door-handle-45.jpg"),
    g("Parking Camera Display", "/gallery/syros-ev/parking-camera-display-136.jpg"),
    g("Speakers", "/gallery/syros-ev/speakers-58.jpg"),
    g("Wireless Charging Pad", "/gallery/syros-ev/wireless-charging-pad-206.jpg"),
    g("Airbags", "/gallery/syros-ev/airbags-94.jpg"),
  ],
};
